CREATE DATABASE BASEDFNE_DFNE_DFE_MONOMISIONAL;

USE BASEDFNE_DFNE_DFE_MONOMISIONAL;

CREATE TABLE LUGARES (
    CODLUGAR INT(2),
    NOMBRELUGAR VARCHAR(20),
    PRIMARY KEY(CODLUGAR)
);

CREATE TABLE MUSICA (
    CODMUSICA INT(2),
    NOMBREMUSICA VARCHAR(20),
    PRIMARY KEY(CODMUSICA)
);

CREATE TABLE CONTRATOSEVENTOS (
    NROCONTRATO INT(10),
    FECHA VARCHAR(15),
    VALOR INT(10),
    PRIMARY KEY(NROCONTRATO)
);

CREATE TABLE CANTANTES (
    CEDULA INT(10),
    NOMBRE VARCHAR(20),
    TELEFONO INT(10),
    CODMUSICA INT(2),
    PRIMARY KEY(CEDULA),
    FOREIGN KEY(CODMUSICA) REFERENCES MUSICA(CODMUSICA)
);

CREATE TABLE BANCO (
    CODBANCO INT(2),
    NOMBREBANCO VARCHAR(20),
    PRIMARY KEY(CODBANCO)
);

CREATE TABLE CONTRATOSEVENTOS_CANTANTES (
    NROCONTRATO INT(10),
    CEDULA INT(10),
    HORASSHOW INT(2),
    PRIMARY KEY(NROCONTRATO, CEDULA),
    FOREIGN KEY(NROCONTRATO) REFERENCES CONTRATOSEVENTOS(NROCONTRATO),
    FOREIGN KEY(CEDULA) REFERENCES CANTANTES(CEDULA)
);

CREATE TABLE PAGOS (
    NUMRECIBO INT(10),
    FECHA VARCHAR(15),
    VALOR INT(10),
    CODBANCO INT(2),
    NROCONTRATO INT(10),
    CEDULA INT(10),
    PRIMARY KEY(NUMRECIBO),
    FOREIGN KEY(CODBANCO) REFERENCES BANCO(CODBANCO),
    FOREIGN KEY(NROCONTRATO) REFERENCES CONTRATOSEVENTOS_CANTANTES(NROCONTRATO),
    FOREIGN KEY(CEDULA) REFERENCES CONTRATOSEVENTOS_CANTANTES(CEDULA)
);